language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: http4k-demo-graal
  api_key:
    secure: g06KYjDllTtC5eTSAVsg2zMYrsa6FbtA0y2eir5qRZy3kWmE/7JQIO4Td2JeTtQGJQbgNFwMyhgXBdYptysk0Cwk2Vy3d9ceyRJd7Xl93XwBdbPUlipl8mrRn1lKjo5IuL9+F/ZYC7ZmgurJ9I8SK3MBSlcgBvq82IrpFuDsjkHxOQ3sv9IIPLBBpkfmx1TjhD03RL5p5i2VO/RLze3yIBJ7amyHHuCun0zUp/rZ64Ku6hwiyGQzabjY9FuKPQld5rsLEOAeml7TXHXIoGWyQPgYeasNEiSnB3Xcfq+sBs+OaoURwqAk4e0cXAUz58OcNS1UPptUTMP9eMEdrS1QeLRPxo64RQfKzk3B6v53mxvD3jDtNg04osGaEsp4kZ/euv/SIgQe0BXalGfHw7pPbnJVV85BGjxkbjIV16d/6Xyreh/vn31PGHSVGc7N1evTDbVjG46uKVwaff2R2kizI5eL5JeAkBg/FTWL0IWvK8EgP05sZVOciTY0CeGzNR7b1IUEwe/8ttZDRFT+oYtf/ka+D21P8t4MtRKUqL4mVk2pzEuMyVxs1FwrLfE0m+pgZBfA7C/r+zCIJXCQ8CdbjItQblvV/V1116xfuqybp68K5u/XExY7yDjQsSV0P8DIXI/MHcbKE/mq8YSfRlfRk5IxTTqBfFhVGkTw3/cW+wk=
