#!/usr/bin/env bash

set -e

./gradlew clean shadowJar

./graalvm/Contents/Home/bin/native-image \
    -H:+ReportUnsupportedElementsAtRuntime \
    -J-Xmx3G -J-Xms3G --no-server \
    -jar build/libs/http4kGraal.jar
